wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: huggingface
    huggingface_version: 3.0.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1637060968
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      4: 3.8.11
      5: 0.12.6
      6: 3.0.2
      8:
      - 5
