# @package _group_

nq_train_only_text:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/plain/nq-train-text-without-special.json"

nq_dev_only_text:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/plain/nq-dev-text-without-special.json"

nq_train_only_table:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/plain/table_train_without_special_token.json"

nq_dev_only_table:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/plain/table_dev_without_special_token.json"

nq_train_with_table:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/plain/nq-train-text-table_without_special_token.json"

nq_dev_with_table:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/plain/nq-dev-text-table_without_special_token.json"

nq_train_with_table_rel:
  _target_: dpr.data.biencoder_data.RelationalJsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/relative_embedding/nq-rel-augmented-train.json"

nq_dev_with_table_rel:
  _target_: dpr.data.biencoder_data.RelationalJsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/relative_embedding/nq-rel-augmented-dev.json"

nq_train_text_only_rel:
  _target_: dpr.data.biencoder_data.RelationalJsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/relative_embedding/nq-rel-augmented-train-text.json"

nq_dev_text_only_rel:
  _target_: dpr.data.biencoder_data.RelationalJsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/relative_embedding/nq-rel-augmented-dev-text.json"

nq_train_table_only_rel:
  _target_: dpr.data.biencoder_data.RelationalJsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/relative_embedding/nq-rel-augmented-train-table.json"

nq_dev_table_only_rel:
  _target_: dpr.data.biencoder_data.RelationalJsonQADataset
  file: "/home/deokhk/research/MultiQA_data/retriever/relative_embedding/nq-rel-augmented-dev-table.json"

nq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-train

nq_train_hn1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-adv-hn-train

nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-dev


trivia_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train

trivia_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-dev

squad1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-train

squad1_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-dev

webq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-train
  
webq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-dev
  
curatedtrec_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-train
  
curatedtrec_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-dev