# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

dpr_wiki_with_table:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: "/home/deokhk/research/MultiQA/model/DPR/dpr/downloads/data/wikipedia_split/psg_table_w100.tsv"
  id_prefix: 'wiki_with_table:'
